# Iceball CMake configuration file
# This file is generated by CMake and should not be edited manually



# Include the exported targets
include("${CMAKE_CURRENT_LIST_DIR}/iceballTargets.cmake")

# Set variables for backward compatibility
set(ICEBALL_VERSION "0.2.1")
set(ICEBALL_INCLUDE_DIRS "")
set(ICEBALL_LIBRARIES "")

# Check if all required components are available
check_required_components(iceball)

# Print status message
message(STATUS "Found Iceball version 0.2.1")
